### ISSUE TITLE
Use longer time frame for metrics by default

### ISSUE THREAD

**Issue by oskarth** [status-im/analytics.status.im#4]
E.g. week over week, day to day not interesting.

See 
![image](https://user-images.githubusercontent.com/1552237/47114203-c3ae4580-d28d-11e8-9542-c3f574249a59.png)

Should be week 30..week 40 etc.

**Comment by tersec** [comment]
Yes, from the beginning there's been code to create weekly charts, per discussions with @chadyj. There's just not the data to create them yet, since Whisper monitoring got reset as of October 5th when @jakubgs set up. But https://github.com/status-im/analytics-dash/blob/develop/prometheus.py#L125 has been creating weekly charts since I created that script, and they can be displayed whenever they begin to be useful, or even before that, if that's desired.

There's a separate question of whether to continue to create/display hourly charts at all; I'm 100% open to just not do so.

**Comment by jakubgs** [comment]
Outdated.
